language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_c6f042e7558e_key -iv $encrypted_c6f042e7558e_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
